# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='bar',
  serialized_pb='\n\rexample.proto\x12\x03\x62\x61r\"4\n\tSimpleMsg\x12\x0b\n\x03\x66oo\x18\x01 \x02(\t\x12\x0c\n\x04\x66izz\x18\x02 \x01(\x05\x12\x0c\n\x04\x62uzz\x18\x03 \x03(\x08\x42\x02H\x03')




_SIMPLEMSG = _descriptor.Descriptor(
  name='SimpleMsg',
  full_name='bar.SimpleMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='foo', full_name='bar.SimpleMsg.foo', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fizz', full_name='bar.SimpleMsg.fizz', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='buzz', full_name='bar.SimpleMsg.buzz', index=2,
      number=3, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=22,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['SimpleMsg'] = _SIMPLEMSG

class SimpleMsg(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIMPLEMSG

  # @@protoc_insertion_point(class_scope:bar.SimpleMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\003')
# @@protoc_insertion_point(module_scope)
